import type { PublishedResume } from "@/lib/resume/types";

export const fallbackResume: PublishedResume = {
  profile: {
    id: "fallback-resume",
    slug: "sample-resume",
    locale: "zh-CN",
    title: "个人简历",
    ownerName: "林澈",
    headline: "全栈工程师 / AI 应用开发者",
    summary:
      "关注可落地的 AI 产品、数据驱动的业务系统和体验友好的前端界面。擅长把模糊需求拆成可验证的产品路径，并用 Next.js、TypeScript 和 PostgreSQL 快速交付可维护版本。",
    avatarUrl: null,
    location: "上海 / 远程协作",
    email: "hello@example.com",
    phone: "+86 138 0000 0000",
    websiteUrl: "https://example.com",
    githubUrl: "https://github.com/example",
    linkedinUrl: "https://www.linkedin.com",
    createdAt: "2026-05-07",
    updatedAt: "2026-05-07",
  },
  links: [
    {
      id: "fallback-link-website",
      label: "作品集",
      url: "https://example.com",
      icon: "website",
      sortOrder: 1,
    },
    {
      id: "fallback-link-github",
      label: "GitHub",
      url: "https://github.com/example",
      icon: "github",
      sortOrder: 2,
    },
    {
      id: "fallback-link-linkedin",
      label: "LinkedIn",
      url: "https://www.linkedin.com",
      icon: "linkedin",
      sortOrder: 3,
    },
  ],
  skillGroups: [
    {
      id: "fallback-skill-ai",
      name: "AI 应用",
      description: "从原型到生产的 LLM 应用交付能力",
      sortOrder: 1,
      items: [
        {
          id: "fallback-skill-rag",
          name: "RAG / Agent",
          level: "expert",
          keywords: ["检索评测", "工具调用", "上下文工程"],
          sortOrder: 1,
        },
        {
          id: "fallback-skill-prompt",
          name: "Prompt Engineering",
          level: "expert",
          keywords: ["结构化输出", "安全边界", "失败恢复"],
          sortOrder: 2,
        },
      ],
    },
    {
      id: "fallback-skill-fullstack",
      name: "全栈工程",
      description: "偏向类型安全、服务端渲染和清晰数据边界",
      sortOrder: 2,
      items: [
        {
          id: "fallback-skill-next",
          name: "Next.js / React",
          level: "expert",
          keywords: ["App Router", "Server Actions", "RSC"],
          sortOrder: 1,
        },
        {
          id: "fallback-skill-db",
          name: "PostgreSQL / Neon",
          level: "proficient",
          keywords: ["Schema 设计", "查询优化", "Serverless DB"],
          sortOrder: 2,
        },
      ],
    },
    {
      id: "fallback-skill-product",
      name: "产品交付",
      description: "用验证路径降低不确定性",
      sortOrder: 3,
      items: [
        {
          id: "fallback-skill-prd",
          name: "PRD / 技术方案",
          level: "proficient",
          keywords: ["里程碑", "验收标准", "风险拆解"],
          sortOrder: 1,
        },
        {
          id: "fallback-skill-design",
          name: "UI 体验落地",
          level: "proficient",
          keywords: ["响应式", "可访问性", "设计系统"],
          sortOrder: 2,
        },
      ],
    },
  ],
  workExperiences: [
    {
      id: "fallback-work-1",
      company: "示例科技",
      role: "高级全栈工程师",
      location: "上海",
      employmentType: "full_time",
      startDate: "2023-04-01",
      endDate: null,
      isCurrent: true,
      summary:
        "负责 AI 业务工具、内部数据平台和客户侧 Web 应用的架构与交付。",
      highlights: [
        "主导从需求澄清、Schema 设计到上线验证的端到端流程。",
        "搭建 LLM 工具调用链路，使运营任务处理时间下降约 40%。",
        "推动前端组件化和类型收敛，降低跨模块修改成本。",
      ],
      sortOrder: 1,
    },
    {
      id: "fallback-work-2",
      company: "云端实验室",
      role: "前端工程师",
      location: "杭州",
      employmentType: "full_time",
      startDate: "2020-07-01",
      endDate: "2023-03-01",
      isCurrent: false,
      summary: "参与多端业务后台、数据看板和增长实验页面建设。",
      highlights: [
        "沉淀表单、表格和状态反馈模式，提升重复页面交付速度。",
        "优化首屏加载和交互反馈，核心页面 Lighthouse 评分稳定在 90+。",
      ],
      sortOrder: 2,
    },
  ],
  projects: [
    {
      id: "fallback-project-agent",
      slug: "agent-workbench",
      name: "Agent Workbench",
      role: "架构与核心开发",
      description:
        "面向团队内部的 AI 工作台，支持任务编排、工具调用、结果审阅和运行日志追踪。",
      techStack: ["Next.js", "TypeScript", "PostgreSQL", "LLM"],
      highlights: [
        "把复杂工作流拆成可观测步骤，便于人工介入和回滚。",
        "提供统一的提示词、工具和评测入口。",
      ],
      projectUrl: "https://example.com",
      sourceUrl: "https://github.com/example/agent-workbench",
      startDate: "2025-01-01",
      endDate: "2025-08-01",
      isFeatured: true,
      sortOrder: 1,
    },
    {
      id: "fallback-project-resume",
      slug: "next-resume",
      name: "Next Resume",
      role: "全栈开发",
      description:
        "基于 Next.js 和 Neon 的结构化个人简历应用，支持服务端渲染、联系消息写入和打印友好样式。",
      techStack: ["Next.js", "shadcn/ui", "Neon", "Tailwind CSS"],
      highlights: [
        "用 Server Components 读取公开简历数据。",
        "使用 Server Actions 处理联系表单提交。",
      ],
      projectUrl: "https://example.com",
      sourceUrl: "https://github.com/example/next-resume",
      startDate: "2026-05-01",
      endDate: null,
      isFeatured: true,
      sortOrder: 2,
    },
  ],
  education: [
    {
      id: "fallback-education-1",
      school: "示例大学",
      degree: "本科",
      major: "计算机科学与技术",
      location: "南京",
      startDate: "2016-09-01",
      endDate: "2020-06-01",
      description: "系统学习软件工程、数据库、网络和人机交互基础。",
      sortOrder: 1,
    },
  ],
  certifications: [
    {
      id: "fallback-cert-1",
      title: "AI 应用工程实践认证",
      issuer: "示例认证机构",
      issuedOn: "2025-09-01",
      credentialUrl: "https://example.com",
      sortOrder: 1,
    },
  ],
};
